// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.work.vladimirs.proto;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  java.util.List<Person>
      getPeopleList();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  Person getPeople(int index);
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  java.util.List<? extends PersonOrBuilder>
      getPeopleOrBuilderList();
  /**
   * <code>repeated .protobuf.Person people = 1;</code>
   */
  PersonOrBuilder getPeopleOrBuilder(
      int index);
}
